# Generated by Django 3.0.8 on 2020-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendor_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
